[package]
name = "chris-math"
version = "0.1.0"
edition = "2021"
authors=["shadawo <ribe.thibaut@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen="0.2.78"
sha2 = "0.10.2"
hex-literal = "0.3.4"
